### ISSUE TITLE
Feature SonarQube Binding Configuration in Multi-Project setup

### ISSUE THREAD

**Issue by chthoms** [GEBIT/autoconfig-intellij-plugin#8]
It is currently not possible to configure a separate SonarQube Binding for multiple projects in intellij in an "easy" way.

In order to achieve this, each maven-module must override the SonarQube binding, this is not desirable for a project with a lot maven-modules. It is not sufficient to overwrite the parent maven-module or only a single maven-module. (Shift+Alt+S -> Tools -> SonarLint -> Project Settings)

It would be nice if overwriting the SonarQube binding can be configured automatically.

Note: The SonarQube Binding requires a default binding, so assuming a setup up with 2 Projects: ProjA, ProjB
ProjA should configure and use the default binding.
ProjB should configure the overwriting of the binding for each module.

If a third project ProjC is added, it should be configurable the same way as ProjB.

**Comment by nailujx86** [comment]
When configuring module-overrides in the SonarLint-plugin these settings are persisted in the modules *.iml-file with the key `SonarLintModuleSettings`.
Would it be enough to just commit this file into your versioning system if you want to share these module overrides with other people?  
According to the IntelliJ-Documentation the *.iml-files are meant to be shared in the new directory-based project format: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems  
See also https://www.jetbrains.com/help/idea/creating-and-managing-modules.html

**Comment by chthoms** [comment]
If sharing .iml files is fine, this will work, thanks.

**Comment by nailujx86** [comment]
It might work but it would be still annoying to define a module override for every single module.
I've opened an issue/feature suggestion here: https://community.sonarsource.com/t/workspace-inherited-binding-override-support-for-intellij/

**Comment by swesteme** [comment]
As determining the module hierarchy in IntelliJ plugins does not seem to be an option, we may have to implement an autoconfig solution instead of submitting a SonarLint pull request.
